# This is a one-off workflow to set up everything we need to deploy Docker images
# with CDK. This workflow deploys everything that is not specific to a certain
# environment (staging, prod, ...).
name: 02 - Create API Gateway

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment in which to deploy the specific environment resources.'
        required: true
        default: 'development'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy aPI Gateway
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk/reservation-infra
        run: npm install

      - name: Deploy CDK bootstrap stack
        working-directory: cdk/reservation-infra
        run: npm run gateway:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}


